#!/usr/bin/env bash
# fizzbuzzbuzz man

i=1
until [ $i -gt 100 ]
do
	echo $i
	i=$((i + 1))
	if (( i % 3 == 0 )) && (( i % 5 == ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	fi
	
done
