#!/usr/bin/env bash
# print Best School 10 times, print Hi on the 9th
counter=1
while [ $counter -le 10 ]
do
  echo "Best School"
  ((counter++))
	if 
	 $counter=9
	then
	 echo 'Best School'
	\n 
	echo 'Hi'
	fi
done
