#!/usr/bin/env bash
# displays Best School 10 times, displays bad luck on 4th iterartion and good luck on 8th iteration
for i in {1 .. 10}
while [ i -le 10 ]
do
	if [ $i -eq 4 ]; then
		echo 'bad luck'
	elif [ $i -eq 8 ]; then
		echo 'good luck'
	else
		echo 'Best School'
	fi
done
