#!/usr/bin/env bash
# Superstitious numbers!!
i=1
while [ $i -le 20 ]
	if [ $i -e 4 ]; then
	do 
		echo \n 'bad luck from China'
	elif [ $i -e 9 ]; then
	do 
		echo \n 'bad luck from Japan'
	elif [ $i -e 17 ]; then
	do 
		echo \n 'bad luck from Italy'
	fi
done
