#!/usr/bin/env bash
# Clocks!

h=0
m=1

echo "Hour: $h"

while [ $h -le 12 ]
do
	echo $m 
	m=$((m + 1))
	if [ $m -eq 60 ]
	then 
		h=$((h + 1))
		if [ $h -lt 13 ]
		then
			echo "Hour: $h"
		fi
	m=1	
fi
done
