#!/usr/bin/env bash
# Clocks!

hour=1
counter=1

while [ $hour -le 12 ]
do
  echo $counter
  counter=$((counter + 1))

  if [ $counter -eq 60 ]
  then
    echo "Hour: $hour"
    hour=$((hour + 1))
    counter=1

    if [ $hour -eq 13 ]
    then
      break
    fi
  fi
done
