#!/usr/bin/env bash
# Clocks!

hour=1
counter=1

while [ $counter -le 59 ]
do
  echo $counter
  counter=$((counter + 1))

  if [ $counter -eq 60 ]
  then
    echo "Hour: $hour"
    hour=$((hour + 1))
    counter=1
  fi
done
