#!/usr/bin/env bash
# hmm many things are happening here yes

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command";rm -f /var/run/myscript.pid; exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
while true
do
	echo 'To infinity and beyond'
done
trap SIGQUIT SIGTERM
